"""Generate and audit the P8.C2 three-validator rule matrix."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "docs" / "schema-contract-rules.json"
EVIDENCE = ROOT / "docs" / "validator-parity-evidence.json"
PLATFORMS = ("python", "kotlin", "swift")
STATUSES = {"complete", "partial", "missing"}


def schema_bundle_errors() -> list[str]:
    from generate_native_v2_schema_bundle import framed_digest, schema_files

    digest = framed_digest(schema_files())
    python_source = (ROOT / "src/storage/validation/manifest.py").read_text()
    match = re.search(r'^TRUSTED_SCHEMA_SHA256 = "([0-9a-f]{64})"$', python_source, re.MULTILINE)
    errors = [] if match and match.group(1) == digest else ["Python trusted schema digest is stale"]
    for path in (
        ROOT / "droid/app/src/main/java/com/storyteller/droid/engine/TrustedV2Schemas.kt",
        ROOT / "ios/StoryTeller/Engine/TrustedV2Schemas.swift",
    ):
        if not path.exists() or digest not in path.read_text():
            errors.append(f"native trusted schema bundle is stale: {path}")
    return errors


def load_matrix(
    rules_path: Path = RULES,
    evidence_path: Path = EVIDENCE,
) -> tuple[list[dict[str, Any]], tuple[str, ...]]:
    inventory = json.loads(rules_path.read_text())["validator_rules"]
    evidence = json.loads(evidence_path.read_text()).get("rules", {})
    rule_ids = {rule["id"] for rule in inventory}
    errors = [f"unknown parity rule: {rule_id}" for rule_id in sorted(set(evidence) - rule_ids)]
    rows: list[dict[str, Any]] = []
    for rule in sorted(inventory, key=lambda item: item["id"]):
        platforms: dict[str, dict[str, str]] = {}
        supplied = evidence.get(rule["id"], {})
        unknown_platforms = set(supplied) - set(PLATFORMS)
        errors.extend(
            f"{rule['id']}: unknown platform {platform}" for platform in sorted(unknown_platforms)
        )
        for platform in PLATFORMS:
            record = supplied.get(platform, {"status": "missing", "evidence": ""})
            status = record.get("status")
            proof = record.get("evidence", "")
            if status not in STATUSES:
                errors.append(f"{rule['id']}/{platform}: invalid status {status!r}")
            if status in {"complete", "partial"} and not proof:
                errors.append(f"{rule['id']}/{platform}: {status} requires evidence")
            platforms[platform] = {"status": status, "evidence": proof}
        rows.append({**rule, "platforms": platforms})
    return rows, tuple(errors)


def build_report() -> str:
    rows, errors = load_matrix()
    if errors:
        raise ValueError("; ".join(errors))
    lines = [
        "# V2 Validator Parity",
        "",
        "Generated by `scripts/audit_v2_validator_parity.py`. Missing means no reviewed",
        "implementation evidence has been recorded; it does not infer absence from filenames.",
        "",
        "| Rule | Python | Kotlin | Swift | Source |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        cells = []
        for platform in PLATFORMS:
            record = row["platforms"][platform]
            proof = f" (`{record['evidence']}`)" if record["evidence"] else ""
            cells.append(f"{record['status']}{proof}")
        lines.append(
            f"| `{row['id']}` | {cells[0]} | {cells[1]} | {cells[2]} | `{row['source']}` |"
        )
    complete = sum(
        all(row["platforms"][platform]["status"] == "complete" for platform in PLATFORMS)
        for row in rows
    )
    lines.extend(["", f"Three-platform complete: **{complete}/{len(rows)}**.", ""])
    return "\n".join(lines)


def main() -> int:
    rows, errors = load_matrix()
    errors = (*errors, *schema_bundle_errors())
    if errors:
        print("P8.C2 parity inventory invalid:")
        print("\n".join(errors))
        return 1
    complete = sum(
        all(row["platforms"][platform]["status"] == "complete" for platform in PLATFORMS)
        for row in rows
    )
    print(f"P8.C2 validator parity inventory passed ({complete}/{len(rows)} complete)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
