#!/usr/bin/env python3
"""Generate identical, digest-pinned v2 schema sources for Android and iOS."""
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas" / "v2"
KOTLIN = (
    ROOT / "droid/app/src/main/java/com/storyteller/droid/engine/TrustedV2Schemas.kt"
)
SWIFT = ROOT / "ios/StoryTeller/Engine/TrustedV2Schemas.swift"


def schema_files() -> list[Path]:
    return sorted(SCHEMAS.glob("*.schema.json"), key=lambda path: path.name.encode("utf-8"))


def framed_digest(files: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in files:
        name = path.name.encode("utf-8")
        data = path.read_bytes()
        digest.update(len(name).to_bytes(4, "big"))
        digest.update(name)
        digest.update(len(data).to_bytes(8, "big"))
        digest.update(data)
    return digest.hexdigest()


def kotlin_source(files: list[Path], digest: str) -> str:
    rows = [
        f'        "{path.name}" to "{base64.b64encode(path.read_bytes()).decode()}",'
        for path in files
    ]
    return "\n".join([
        "// Generated by scripts/generate_native_v2_schema_bundle.py; do not edit.",
        "package com.storyteller.droid.engine", "", "import java.util.Base64", "",
        "internal object TrustedV2Schemas {",
        f'    const val digest = "{digest}"',
        "    private val encoded = mapOf(", *rows, "    )",
        "    val documents: Map<String, ByteArray> by lazy {",
        "        encoded.mapValues { Base64.getDecoder().decode(it.value) }", "    }", "}", "",
    ])


def swift_source(files: list[Path], digest: str) -> str:
    rows = [
        f'        "{path.name}": "{base64.b64encode(path.read_bytes()).decode()}",'
        for path in files
    ]
    return "\n".join([
        "// Generated by scripts/generate_native_v2_schema_bundle.py; do not edit.",
        "import Foundation", "", "enum TrustedV2Schemas {",
        f'    static let digest = "{digest}"',
        "    private static let encoded: [String: String] = [", *rows, "    ]",
        "    static let documents: [String: Data] = encoded.mapValues {",
        "        Data(base64Encoded: $0)!", "    }", "}", "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = schema_files()
    if len(files) != 25:
        raise SystemExit(f"expected 25 v2 schemas, found {len(files)}")
    digest = framed_digest(files)
    outputs = {KOTLIN: kotlin_source(files, digest), SWIFT: swift_source(files, digest)}
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text() != content
    ]
    if args.check:
        if stale:
            paths = ", ".join(str(path) for path in stale)
            raise SystemExit("stale native schema bundle: " + paths)
    else:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print(f"native v2 schema bundle passed ({len(files)} schemas, sha256={digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
