"""MusicGenerator interface — generates ABC notation from scene descriptions."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MusicGenerator(Protocol):
    """Generates ABC music notation from scene descriptions.

    ABC notation is generated by an LLM (TextGenerator). The pipeline
    converts ABC to MIDI via music21 — no LLM involved in conversion.
    """

    provider: str  # e.g., "abc_notation"

    async def generate(
        self,
        scene_text: str,
        mood: str,
        seed: int | None = None,
    ) -> str:
        """Generate ABC notation for a scene.

        Args:
            scene_text: The text of the scene.
            mood: The emotional tone (e.g., "tense", "peaceful", "triumphant").
            seed: RNG seed for reproducibility.

        Returns:
            Raw ABC notation string starting with "X:1".
        """
        ...

    @staticmethod
    def abc_to_midi(abc_notation: str) -> bytes:
        """Convert ABC notation to MIDI bytes.

        Uses music21 for conversion. No LLM involved.
        """
        ...

    @staticmethod
    def validate_abc(abc_notation: str) -> bool:
        """Check if ABC notation is syntactically valid and playable."""
        ...
